### ISSUE TITLE
Feature Request:  Cockpit/Control Seat display

### ISSUE THREAD

**Issue by Shadowpheonix** [dlaflotte/OreFinderPlus#15]
I would love to be able to use a screen in a cockpit or control seat for OFP instead of (or in addition to) a dedicated LCD.

**Comment by dlaflotte** [comment]
Great request.  Let me look into it.  Thanks for posting.

**Comment by dlaflotte** [comment]
All set.   Version 1.5 now supports cockpits and requires no external LCD's.  Pushing to Steam now.

**Comment by dlaflotte** [comment]
P.S. I've done some QA on it but if you test it out and it works let me know and I'll close the issue out.

**Comment by dlaflotte** [comment]
OK after a bit more testing it seems to work fine.   Let me know what you think but for now I'll close this issue out.
