### ISSUE TITLE
Unable To Use PB Screen.

### ISSUE THREAD

**Issue by Radar5k** [dlaflotte/OreFinderPlus#17]
I've been having problems getting OFP to use the Programmable Block's screen to display info.

I initially tried using only the PB's screen, but it threw an exception: "No LCD's or Cockpits found with the OFP tag name".

I then set the tag name in both the cockpit, and the PB, which gives me the default screen in the cockpit, but still fails to show any data on the PB's screen.

I'll dig through the code, and try to add the right surface to RegisterLCDs(), ClearLCD(), and RefreshScreens() to see what I end up breaking.

Have fun!  =8^)

**Comment by dlaflotte** [comment]
Ahh yeah not sure I grab the surface on the PB.  Cool let me know what you find.   If I get some time this weekend I'll take a look as well.   Thanks for looking into it and for using the Ingame Script!

**Comment by Radar5k** [comment]
I worked out the changes that needed to be made, and it's doing the job nicely.
I've attached the edited script, and am closing this issue.
(Note for future readers, this is for version 1.7 only).

[OFP.zip](https://github.com/dlaflotte/OreFinderPlus/files/6025770/OFP.zip)

**Comment by dlaflotte** [comment]
Awesome thanks Radar5k.  I'll merge it into the code and upload to steam.  Thanks for looking into this.

**Comment by dlaflotte** [comment]
I've added this to the base repository and added it to the steam workshop.  I've also given you credit for the code and thanks for helping out I appreciate it.   Hit me up in steam if you want or have new features you'd like as well.

**Comment by Radar5k** [comment]
Cool. It's easy to CPE clearly written code ;) 

Just looking at your wishlist in the issues... Particularly the one about having the ministatus on the PB screen, so will drop a few lines in there.

**Comment by dlaflotte** [comment]
Cool looking forward to it :)  Thanks.
